# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0006_options_cookie_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='cookie_timeout',
            field=models.IntegerField(default=36000),
        ),
    ]
