# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0008_auto_20180926_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='weixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(blank=True, max_length=50)),
                ('agentid', models.CharField(blank=True, max_length=50)),
                ('redirect_uri', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('corpid', models.CharField(blank=True, max_length=100)),
                ('corp_secret', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='options',
            name='agentid',
        ),
        migrations.RemoveField(
            model_name='options',
            name='appid',
        ),
        migrations.RemoveField(
            model_name='options',
            name='redirect_uri',
        ),
        migrations.RemoveField(
            model_name='options',
            name='state',
        ),
    ]
