# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-14 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='organizations',
            new_name='base_dn',
        ),
    ]
