# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0002_auto_20180914_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='sys_admin',
            field=models.TextField(blank=True),
        ),
    ]
