# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0004_webs'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='cookie_domain',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
