# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0005_options_cookie_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='cookie_timeout',
            field=models.IntegerField(default=10),
        ),
    ]
